### ISSUE TITLE
USER STORY: Create and setup initial workspace

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki#2]
As a **Developer** I can **create a developing workspace** so that **I can start building the frontend**

## Acceptance Criteria 1
**Given** that we need to build a frontend for this project
**When** we have built the API backend
**Then** we can start to develop the frontend

## Acceptance Criteria 2
**Given** that this project is based on a project from Code Institute 
**When** it based on specific versions of modules and template
**Then** we will use the same versions and template for this project

## Tasks
- [ ]  Task 1 – Create a project in Github call kkimages as an exmaple
- [ ]  Task 2 – Launch Github and install React template from Code Institute as follow:
'npx create-react-app . --template git+https://github.com/Code-Institute-Org/cra-template-moments.git --use-npm'
- [ ]  Task 3 – Install Gitpod extension ES7 React/Redux/GraphQl/React-Native
- [ ]  Task 4 – Install Gitpod extension Prettier - (Code formatter)
- [ ]  Task 5 – Install bootstrap 'npm install react-bootstrap@1.6.3 bootstrap@4.6.0'

## EPIC
1. kkwong44/kkimage-frontend#51
