### ISSUE TITLE
USER STORY: Create Initial Project to host the Frontend

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kki#3]
As a **Developer** I can **deploy my Frontend project to Heroku** so that **it can be hosted online***

## Acceptance Criteria 1
**Given** that the project will be shared to the public
**When** the project is ready to deploy
**Then** we can use Heroku to host our project

## Tasks
- [ ]  Task 1 – Signin to heroku and create an app
- [ ]  Task 2 – Connect Github project and deploy
- [ ]  Task 3 – Test connection

## EPIC
1. kkwong44/kkimage-frontend#51
